export const DEFAULT_TEXTS = {
    header: {
        brand: "BDE Sup'RNova",
        ctaBuyCard: "Acheter la carte",
        nav: {
            home: "Accueil",
            events: "Événements",
            partners: "Partenaires",
            card: "Carte BDE",
            team: "L'Équipe",
            contact: "Contact",
        },
    },
    footer: {
        schoolLine: "BDE de l'école Sup'De Vinci Rennes",
        associationTypeBadge: "Association loi 1901",
        navigation: "Navigation",
        contact: "Contact",
        social: "Réseaux sociaux",
        nav: {
            home: "Accueil",
            events: "Événements",
            partners: "Partenaires",
            team: "L'Équipe",
        },
        legal: {
            copyright: "© {year} {association}. Tous droits réservés.",
            mentions: "Mentions légales",
            privacy: "Politique de confidentialité",
        },
    },
    home: {
        brandAltBde: "Logo BDE Sup'RNova",
        brandAlt: "Logo Sup'RNova",
        badgeYearPrefix: "Année",
        title: "Vivez votre vie étudiante à 100%",
        subtitle: "Soirées, voyages, sport et bons plans",
        description: "Rejoignez l'aventure Sup'RNova et profitez d'une année inoubliable avec plus de {partnersCount} partenaires à Rennes.",
        ctaViewEvents: "Voir les événements",
        ctaSeeAdvantages: "Voir les avantages",
        scrollDownAria: "Défiler vers le bas",
        presentation: {
            title: "L'Esprit Sup'RNova",
            convivialityTitle: "Convivialité",
            convivialityText: "Des moments de partage et de rencontre pour souder la promo.",
            eventsTitle: "Événements",
            eventsText: "Des soirées et des activités toute l'année pour décompresser.",
            engagementTitle: "Engagement",
            engagementText: "Une équipe dévouée pour vous représenter et vous animer.",
            intro: "Le BDE Sup'RNova, c'est votre allié pour une vie étudiante riche et dynamique.",
        },
        upcoming: {
            title: "À venir",
            subtitle: "Ne manquez pas nos prochains événements !",
        },
        past: {
            title: "C'était le feu 🔥",
            subtitle: "Retour en images sur nos derniers événements",
            completed: "Terminé",
            photos: "Voir les photos",
            details: "Détails",
            moreComing: "Et bien plus encore à venir...",
        },
        card: {
            title: "Carte BDE {year}",
            subtitle: "Rentabilisée en 2 sorties !",
            description: "Profitez de réductions exclusives chez nos {partnersCount} partenaires : bars, restos, loisirs...",
            ctaBuy: "Je la veux !",
            ctaSeePartners: "Voir les partenaires",
            badges: ["+ de {partnersCount} partenaires", "Remboursée rapidement", "Tarifs préférentiels"],
        },
        team: {
            title: "Votre BDE",
            meet: "Rencontrez l'équipe",
            hero: "Mandat {year}",
            heroSubtitle: "Une équipe motivée pour vous servir",
        },
        teamImageAlt: "Photo de l'équipe du BDE",
        contact: {
            title: "Nous contacter",
            subtitle: "Une question ? Une suggestion ? On est là !",
            email: "Email",
            instagram: {
                title: "Instagram",
                subtitle: "Suivez nos actus",
            },
            discord: {
                title: "Discord",
                subtitle: "Rejoignez la commu",
            },
        },
        accessibility: {
            menu: "Menu",
        },
    },
};
